# Generated by Django 3.0.8 on 2020-07-18 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antivirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus', models.CharField(max_length=25)),
                ('versao', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Antí-virus',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('ip', models.CharField(max_length=15)),
                ('serial', models.IntegerField(blank=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
            ],
            options={
                'verbose_name_plural': 'Switches',
            },
        ),
        migrations.CreateModel(
            name='RelogioPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('ip', models.CharField(max_length=15)),
                ('serial', models.IntegerField(blank=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
            ],
            options={
                'verbose_name_plural': 'Relógios Ponto',
            },
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Status')),
            ],
            options={
                'verbose_name_plural': 'Impressoras',
            },
        ),
        migrations.CreateModel(
            name='DispositivosDeRede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Status')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Tipo')),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='ControleDeAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('ip', models.CharField(max_length=15)),
                ('serial', models.IntegerField(blank=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
            ],
            options={
                'verbose_name_plural': 'Controle de Acessos',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=25)),
                ('patrimonio', models.IntegerField(blank=True)),
                ('locado', models.CharField(choices=[('L', 'Locado'), ('NL', 'Patrimônio')], max_length=255)),
                ('antivirus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Antivirus')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Status')),
                ('tipo', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Tipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('serial', models.IntegerField(blank=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
            ],
            options={
                'verbose_name_plural': 'Coletores',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=15)),
                ('serial', models.IntegerField(blank=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
            ],
            options={
                'verbose_name_plural': 'Câmeras',
            },
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Host')),
                ('serial', models.IntegerField(blank=True)),
                ('mac_address', models.CharField(max_length=20)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.Modelo')),
            ],
            options={
                'verbose_name_plural': 'Access Points',
            },
        ),
    ]
