# Generated by Django 2.2 on 2020-08-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controledeacesso',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='relogioponto',
            name='modelo',
        ),
        migrations.DeleteModel(
            name='Coletor',
        ),
        migrations.DeleteModel(
            name='ControleDeAcesso',
        ),
        migrations.DeleteModel(
            name='RelogioPonto',
        ),
    ]
