# Generated by Django 2.2 on 2020-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_auto_20200731_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='localizacao',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
