# Generated by Django 2.2 on 2020-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_impressora_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='serial',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='conf',
            field=models.FileField(default=0, upload_to='ap_conf/%d-%m-%Y'),
            preserve_default=False,
        ),
    ]
