# Generated by Django 2.2 on 2020-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutMenssageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True, verbose_name='Data da adição')),
                ('email_contact_text', models.TextField(verbose_name='Texto de contato para E-mail')),
                ('address_contact_url', models.EmailField(max_length=254, verbose_name='Texto de contato para Endereço')),
                ('phone_contact_text', models.TextField(verbose_name='Texto de contato para telefone')),
            ],
            options={
                'verbose_name_plural': 'Mensagem do Layout de Contato',
            },
        ),
        migrations.CreateModel(
            name='LayoutMenssagePresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True, verbose_name='Data da adição')),
                ('presentation_text', models.TextField(verbose_name='Texto de Apresentação da Aplicação')),
            ],
            options={
                'verbose_name_plural': 'Mensagem do Layout de Apresentação',
            },
        ),
    ]
