# Generated by Django 2.2 on 2020-07-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutmenssagecontact',
            name='address_contact_url',
            field=models.TextField(verbose_name='Texto de contato para Endereço'),
        ),
        migrations.AlterField(
            model_name='layoutmenssagecontact',
            name='email_contact_text',
            field=models.EmailField(max_length=254, verbose_name='Texto de contato para E-mail'),
        ),
    ]
