# Generated by Django 2.2 on 2020-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_page', '0002_auto_20200730_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutmenssagecontact',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da adição'),
        ),
        migrations.AlterField(
            model_name='layoutmenssagepresentation',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da adição'),
        ),
    ]
