# Generated by Django 2.2 on 2020-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_page', '0004_auto_20200730_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutMenssage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data da adição')),
                ('presentation_text', models.TextField(verbose_name='Texto de Apresentação da Aplicação')),
                ('email_contact_text', models.EmailField(max_length=254, verbose_name='Texto de contato para E-mail')),
                ('address_contact_text', models.TextField(verbose_name='Texto de contato para Endereço')),
                ('phone_contact_text', models.TextField(verbose_name='Texto de contato para telefone')),
            ],
            options={
                'verbose_name_plural': 'Mensagem do Layout de Contato',
            },
        ),
        migrations.DeleteModel(
            name='LayoutMenssageContact',
        ),
        migrations.DeleteModel(
            name='LayoutMenssagePresentation',
        ),
    ]
