# Generated by Django 2.2 on 2020-07-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_page', '0006_auto_20200730_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Texto de contato para E-mail')),
            ],
        ),
        migrations.RenameField(
            model_name='layoutmenssagecontact',
            old_name='pk_layout_presentation',
            new_name='fk_layout_presentation',
        ),
        migrations.RemoveField(
            model_name='layoutmenssagecontact',
            name='email_contact_text',
        ),
        migrations.AddField(
            model_name='layoutmenssagecontact',
            name='fk_email_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_home_page.LayoutEmail', verbose_name='Texto de contato para E-mail'),
        ),
    ]
