# Generated by Django 2.2 on 2020-07-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_page', '0007_auto_20200730_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layoutemail',
            options={'verbose_name_plural': 'Mensagem de Apresentação do Email'},
        ),
    ]
