# Generated by Django 2.2.4 on 2020-06-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Endereço'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': 'Cupoms'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Ordem de Compra'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Ordem de Item'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Pagamentos'},
        ),
    ]
