# Generated by Django 2.2.4 on 2020-07-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATI',
            fields=[
                ('ATI_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CE', models.CharField(blank=True, max_length=100, verbose_name='Conhecimento')),
                ('BL', models.CharField(blank=True, max_length=100, verbose_name='BL')),
                ('REPCNPJ', models.CharField(blank=True, max_length=100, verbose_name='Repr. CNPJ')),
                ('REPREZAO', models.CharField(blank=True, max_length=100, verbose_name='Repr. Razão Social')),
                ('EMISSAO', models.CharField(blank=True, max_length=100, verbose_name='Data Emissão')),
                ('SITUACAO', models.CharField(blank=True, max_length=100, verbose_name='Situação')),
                ('MODALIDADE', models.CharField(blank=True, max_length=100, verbose_name='Modalidade Frete')),
                ('pORIGEM', models.CharField(blank=True, max_length=100, verbose_name='Porto Origem')),
                ('psPROCEDE', models.CharField(blank=True, max_length=100, verbose_name='Pais Procedência')),
                ('UFdestino', models.CharField(blank=True, max_length=100, verbose_name='UF Destino')),
                ('MERCADORIA', models.CharField(blank=True, max_length=100, verbose_name='Mercadoria')),
            ],
        ),
        migrations.CreateModel(
            name='CNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNT', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conteiner')),
                ('cntISO', models.CharField(blank=True, max_length=100, verbose_name='ISO')),
                ('cntTipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('cntTara', models.CharField(blank=True, max_length=100, verbose_name='TARA')),
                ('cntPB', models.CharField(blank=True, max_length=100, verbose_name='Peso Bruto')),
                ('m3', models.CharField(blank=True, max_length=100, verbose_name='M3')),
                ('codIMO', models.CharField(blank=True, max_length=100, verbose_name='Codigo IMO')),
                ('clasIMO', models.CharField(blank=True, max_length=100, verbose_name='Classe IMO')),
                ('ID_CNT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.ATI')),
            ],
        ),
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, upload_to='media/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('ATI_ANEXO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.ATI')),
            ],
        ),
    ]
