# Generated by Django 3.0.8 on 2020-07-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Lançamento',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(max_length=40, verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=50, verbose_name='Serviço')),
                ('dt_lancamento', models.DateField(verbose_name='Data de Lançamento')),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('forma_de_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_valores.FormaPagamento', verbose_name='Forma de Pagamento')),
                ('t_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_valores.Empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name_plural': 'Contratos de Serviço',
            },
        ),
    ]
