# Generated by Django 2.2 on 2020-08-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cardapio', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name_plural': 'File Upload'},
        ),
        migrations.AlterModelOptions(
            name='imageupload',
            options={'verbose_name_plural': 'Lista de Imagens'},
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='arquivo',
            field=models.FilePathField(path='D:\\Git\\INTRANET\\media/FilePath/%d-%m-%Y/'),
        ),
    ]
