# Generated by Django 2.2 on 2020-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cardapio', '0004_delete_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='arquivo',
            field=models.ImageField(upload_to='images/%d-%m-%Y'),
        ),
    ]
