# Generated by Django 2.2.14 on 2020-08-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cardapio', '0005_auto_20200801_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='arquivo',
            field=models.FileField(upload_to='images/%d-%m-%Y'),
        ),
    ]
